### ISSUE TITLE
Plugin API, Perm Nodes, Classes, etc.

### ISSUE THREAD

**Issue by JoshMullins** [JoshMullins/MVPGadgets#25]
I would like to plugin to have fully operable permission nodes, to help enable the ability to donate for the gadgets, or win them in other plugins.

Permission Node example:  mvpgadgets.{tool_name}

Tagging @TGRHavoc and @pookeythekid

**Comment by pookeythekid** [comment]
I think this should include a Vault hook in either or both of the following cases:

1. Players can buy the gadgets with money that they win in other games, or maybe some survival shop on a server. I think we all know lots of plugins give money via Vault.

2. Developers can use an MVPGadgets API. In their plugins, they can simply call some kind of player#addGadget(Gadget) method, then, through a Vault permissions hook, MVPGadgets will add the permission node of the corresponding gadget to the player. Maybe for the custom gadget additions (does that still exist?) a requirement will be a permission node for the gadget.

Anyway, I'd love to get started on either of these, but I was planning on plunging into something new after I removed MobCannon from my short list. Another chance to contribute to this project is definitely intriguing, though. I'll get back once I weigh my options, either with a response or a pull request. ;P

**Comment by JoshMullins** [comment]
Thats a great idea. I'd love to see what you have in mind. ;)

**Comment by TGRHavoc** [comment]
@JoshMullins
Would the permission nodes stop the gadgets from appearing in the GUI, not allow the player to select a gadget or just not allow them to use the gadget?

**Comment by JoshMullins** [comment]
@TGRHavoc I was thinking when people scroll over the gadget, their would be a message looking like below.

Color Bomb
An explosion of wool and particles!
Permission: No

Also, do you have Skype?

**Comment by TGRHavoc** [comment]
@JoshMullins
I do, feel free to add me. You should be able to find me by typing "Jordan | TGRHavoc" if not then PM me, i'll send you my username.

**Comment by TGRHavoc** [comment]
> gadget to the player. Maybe for the custom gadget additions (does that still exist?) a requirement will be a permission node for the gadget.

@pookeythekid 
It doesn't because I felt that it wasn't necessary and I thought that it would be too much haste for the other developers (Having to compile into a .class file) however, I think we could implement a loader similar to @TheFreakLord 's slightly modified to load .java classes instead?
As for the permission nodes, I took @JoshMullins advice and made them "mvpgadgets.<gadgetName>" where "<gadgetName>" is the variable "gadgetName" stored in the gadgets. I feel this makes it easier on the server owners as they have the same "gadgetName" throughout their config files.

> Developers can use an MVPGadgets API. In their plugins, they can simply call some kind of player#addGadget(Gadget) method, then, through a Vault permissions hook, MVPGadgets will add the permission node of the corresponding gadget to the player. Maybe for the custom gadget additions (does that still exist?) a requirement will be a permission node for the gadget.
Maybe your next contribution will be the API? :stuck_out_tongue: You seem to be good at commenting code to explain what each methods do and such.

**Comment by JoshMullins** [comment]
Would love to see some API ;)

**Comment by pookeythekid** [comment]
Not /entirely/ related, but I didn't feel like it was worth a new issue.

Could there be a feature list? Or from now on, we start keeping a change log? I'm starting to fall behind with the commits, and I'll probably continue to do so until I get back to Bukkit plugins.

**Comment by JoshMullins** [comment]
A changelog would be a nice commit for the repo. If you would like to create that and bring it up to speed, I will merge the pull request. :)

**Comment by JoshMullins** [comment]
Closing issue.
