### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by JoshMullins** [JoshMullins/MVPGadgets#27]
Please see https://github.com/JoshMullins/MVPGadgets/pull/26
Classes need to be imported for this update to be functional.

@TGRHavoc @TheFreakLord @pookeythekid @bwfcwalshyPluginDev

**Comment by TGRHavoc** [comment]
@JoshMullins
I managed to do this in the last few commits.. I forgot to update the text :P

**Comment by JoshMullins** [comment]
Awesome! Closing this then :)
Also added you on Skype!
