### ISSUE TITLE
Lets Go

### ISSUE THREAD

**Issue by JoshMullins** [JoshMullins/MVPGadgets#34]
Lets get this project back on track @TGRHavoc @pookeythekid

**Comment by pookeythekid** [comment]
You're right, this place has been super quiet. Starting a couple weeks from now I'm on summer break, and I've found some time on my hands otherwise lately. Time for me to start developing again.

**Comment by TGRHavoc** [comment]
Got some spare time this week, what are we prioritizing?

**Comment by pookeythekid** [comment]
New things. I say we get new features into code no matter how bad they are, then debug and add on later. This isn't supposed to be a finished product with a bunch of first-build PRs.

**Comment by TGRHavoc** [comment]
Fair duce. I remember someone mentioning an API earlier in development I was just wondering what features that's supposed to have/allow others to do.

**Comment by pookeythekid** [comment]
I think that was me who mentioned API. I think it would be like people using MobCannon to launch mobs for some other purpose in their plugin, creating their own new Gadgets (which we already have, don't we?...), umm... other things. Perhaps we could make an even <em>simpler</em> API for disguises. I'm not sure if it could possibly be simplified anymore, never worked with DisguiseAPI.

**Comment by pookeythekid** [comment]
Don't feel like it's worth making another issue, so here's my suggestion right here.

Anyone think we should put this project on <a href="http://infernaldevelopers.com/forums/">Infernal Developers</a>? Perhaps you guys have heard of it, a few guys promote it on the Bukkit forums.

**Comment by JoshMullins** [comment]
You are welcome to list the project there as any help is greatly appreciated. I would like to get an initial release of the project out by the end of the month if possible.

**Comment by JoshMullins** [comment]
Closing issue.
